### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by SVGEMS** [sarahkittyy/KeywordTracker#1]
A little inbox button would be really nice, which would list all keyword matches.

**Comment by sarahkittyy** [comment]
This is on my to-do list :)

**Comment by sarahkittyy** [comment]
Finally fixed in 5ce5b437ff4659b237402d89862bb89265a7aaf3 :)

**Comment by RedCMD** [comment]
Sorry. But I cant seem to find the inbox button
Is it Discords inbox?
Cause that fills up instantly for me

**Comment by sarahkittyy** [comment]
@RedCMD For one, BetterDiscord's site has been broken for devs for a bit, so go to settings->plugins and make sure you are on the latest version (v1.2.0)

After that, the button should appear up here:
![image](https://user-images.githubusercontent.com/31551546/130105008-eb8abc16-ee6c-40be-8143-ab29df2935a1.png)

**Comment by RedCMD** [comment]
It does say I have the latest v1.2 version
![image](https://user-images.githubusercontent.com/33529441/130153841-84dc1173-79d0-4f3c-8bb7-28cdaf1a4fe0.png)
I tried redownloading it from the website, your repo and from within the plugin repo in settings
The changelog says it was added, but I still don't see it
![image](https://user-images.githubusercontent.com/33529441/130153786-e59cd944-efe3-4ddd-85b0-d058545834f6.png)

**Comment by RedCMD** [comment]
Can confirm its working now.
Thanks :D
The list of all the old messages showed up
