### ISSUE TITLE
Can't see inbox button on the latest version.

### ISSUE THREAD

**Issue by eoomon** [sarahkittyy/KeywordTracker#14]
![image](https://user-images.githubusercontent.com/89237651/130179091-db3528fb-b78b-430e-8c78-9fdfaaa7d393.png)
![image](https://user-images.githubusercontent.com/89237651/130179133-6f91ca07-b806-4add-9d62-948e3bc04b4d.png)

Do I have to do additional settings?

**Comment by sarahkittyy** [comment]
Could have sworn I fixed this on the latest version, two people this was happening to both reported it stopped occuring. Sometimes it doesn't show up until you switch to a different channel?

**Comment by eoomon** [comment]
Oh.. my BD was crashed and stopped too. And then just launching normal discord. Maybe two days ago.
So I re-installed BD and plugins, no more crashes or stop. 
I have tried switch to various servers and channels but still can't see inbox buttons.

**Comment by ddivito** [comment]
me too guys 
![imagen](https://user-images.githubusercontent.com/25613305/134832807-3304020d-7be9-4c21-a090-d3616b27f1e6.png)

**Comment by smullmull** [comment]
![inbox](https://user-images.githubusercontent.com/95597356/144774647-786b758b-6872-4084-a1af-bb943ade1f6f.png)
unchecking this fixed it for me

**Comment by hkrawczyk** [comment]
> ![inbox](https://user-images.githubusercontent.com/95597356/144774647-786b758b-6872-4084-a1af-bb943ade1f6f.png) unchecking this fixed it for me

where did you find that option?

**Comment by sarahkittyy** [comment]
Probs fixed by now
